version: "3.1"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --innodb-page-size=65536
    # restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=odf
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin_odf
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
  # jsreport:
  #   image: jsreport/jsreport:2.4.0
  #   container_name: jsreport_ticket
  #   ports:
  #     - 5488:5488
  #   volumes:
  #     - .jsreport:/jsreport
